-- MySQL Script generated by MySQL Workbench
-- Fri Nov 20 16:55:38 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema uba_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `uba_db` ;

-- -----------------------------------------------------
-- Schema uba_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `uba_db` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `uba_db` ;

-- -----------------------------------------------------
-- Table `banner_home`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banner_home` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `banner_home` (
  `id_banner` INT NOT NULL,
  `banner` VARCHAR(45) NULL,
  `banner_mobile` VARCHAR(45) NULL,
  `link` VARCHAR(45) NULL,
  PRIMARY KEY (`id_banner`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `newsletter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `newsletter` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `newsletter` (
  `id` INT NOT NULL,
  `whatsapp` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `produtos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `produtos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `produtos` (
  `id_produto` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `preco` VARCHAR(45) NULL,
  `validade_preco` DATETIME NULL,
  `largura` VARCHAR(45) NULL,
  `altura` VARCHAR(45) NULL,
  `profundidade` VARCHAR(45) NULL,
  `cor1` VARCHAR(45) NULL,
  `cor2` VARCHAR(45) NULL,
  `cor3` VARCHAR(45) NULL,
  `cor4` VARCHAR(45) NULL,
  `foto` VARCHAR(45) NULL,
  PRIMARY KEY (`id_produto`))
ENGINE = InnoDB
COMMENT = '	';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `trabalhe_conosco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trabalhe_conosco` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `trabalhe_conosco` (
  `id_curriculo` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NULL,
  `endereco` VARCHAR(45) NULL,
  `sexo` VARCHAR(45) NULL,
  `data_nascimento` VARCHAR(45) NULL,
  `curriculo` VARCHAR(45) NULL,
  PRIMARY KEY (`id_curriculo`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
